# Generated by Django 3.2.25 on 2025-01-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordList', '0002_alter_card_meaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='count_appear',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='出題回数'),
        ),
        migrations.AddField(
            model_name='card',
            name='count_incorrect',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='不正回数'),
        ),
    ]
